usr/lib/kde4/kcm_krunner_audioplayercontrol.so
usr/lib/kde4/kcm_krunner_charrunner.so
usr/lib/kde4/kcm_krunner_dictionary.so
usr/lib/kde4/kcm_krunner_spellcheck.so
usr/lib/kde4/kcm_plasma_runner_events.so
usr/lib/kde4/krunner_audioplayercontrol.so
usr/lib/kde4/krunner_browserhistory.so
usr/lib/kde4/krunner_charrunner.so
usr/lib/kde4/krunner_contacts.so
usr/lib/kde4/krunner_converter.so
usr/lib/kde4/krunner_dictionary.so
usr/lib/kde4/krunner_katesessions.so
usr/lib/kde4/krunner_konquerorsessions.so
usr/lib/kde4/krunner_konsolesessions.so
usr/lib/kde4/krunner_kopete.so
usr/lib/kde4/krunner_mediawiki.so
usr/lib/kde4/krunner_spellcheckrunner.so
usr/lib/kde4/krunner_youtube.so
usr/lib/kde4/plasma_runner_datetime.so
usr/lib/kde4/plasma_runner_events.so
#workaround to stop overlap with files in kamoso
usr/share/icons/hicolor/16x16/actions/youtube.png usr/share/icons/oxygen/16x16/actions/
usr/share/icons/hicolor/22x22/actions/youtube.png usr/share/icons/oxygen/22x22/actions/
usr/share/icons/hicolor/32x32/actions/youtube.png usr/share/icons/oxygen/32x32/actions/
usr/share/icons/hicolor/48x48/actions/youtube.png usr/share/icons/oxygen/48x48/actions/
usr/share/icons/hicolor/64x64/actions/youtube.png usr/share/icons/oxygen/64x64/actions/
usr/share/icons/hicolor/scalable/actions/youtube.svgz usr/share/icons/oxygen/scalable/actions/
usr/share/kde4/services/CharRunner_config.desktop
usr/share/kde4/services/CharacterRunner.desktop
usr/share/kde4/services/browserhistory.desktop
usr/share/kde4/services/katesessions.desktop
usr/share/kde4/services/konquerorsessions.desktop
usr/share/kde4/services/konsolesessions.desktop
usr/share/kde4/services/plasma-runner-audioplayercontrol.desktop
usr/share/kde4/services/plasma-runner-audioplayercontrol_config.desktop
usr/share/kde4/services/plasma-runner-contacts.desktop
usr/share/kde4/services/plasma-runner-converter.desktop
usr/share/kde4/services/plasma-runner-datetime.desktop
usr/share/kde4/services/plasma-runner-dictionary.desktop
usr/share/kde4/services/plasma-runner-dictionary_config.desktop
usr/share/kde4/services/plasma-runner-events.desktop
usr/share/kde4/services/plasma-runner-events_config.desktop
usr/share/kde4/services/plasma-runner-kopete.desktop
usr/share/kde4/services/plasma-runner-spellchecker.desktop
usr/share/kde4/services/plasma-runner-spellchecker_config.desktop
usr/share/kde4/services/plasma-runner-techbase.desktop
usr/share/kde4/services/plasma-runner-wikipedia.desktop
usr/share/kde4/services/plasma-runner-wikitravel.desktop
usr/share/kde4/services/plasma-runner-youtube.desktop
