usr/share/kde4/services/plasma-containment-groupingdesktop.desktop
usr/share/kde4/services/plasma-containment-groupingpanel.desktop
usr/share/kde4/services/plasma-containment-griddesktop.desktop
usr/lib/libplasma_groupingcontainment.so.4
usr/lib/libplasma_groupingcontainment.so.4.6.0
usr/lib/kde4/plasma_containment_groupingpanel.so
usr/lib/kde4/plasma_containment_griddesktop.so
usr/lib/kde4/plasma_containment_groupingdesktop.so
