#!/bin/sh
set -e

ua_remove () {
	update-alternatives \
        --remove xinput-$1 \
        /etc/X11/xinit/xinput.d/$2 ;
}

case "$1" in
    remove|upgrade|deconfigure)
        ua_remove all_ALL ibus-kde
        ua_remove ja_JP   ibus-kde
        ua_remove ko_KR   ibus-kde
        ua_remove zh_CN   ibus-kde
        ua_remove zh_TW   ibus-kde
        ua_remove zh_HK   ibus-kde
        ua_remove zh_SG   ibus-kde
	;;
    failed-upgrade)
	;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
   ;;
esac

#DEBHELPER#

exit 0
